// SPDX-FileCopyrightText: 2026 The BAR Lobby Authors
//
// SPDX-License-Identifier: MIT

// Changes to this config schema's defaults will require a new config version to be deployed.
// CI should use tools/generate-diff-config.ts to create a config diff for this purpose.

import { Type, Static } from "@sinclair/typebox";

export const configSchema = Type.Object({
    // Note, configUrl is required and must match the expected location or else Github Actions will not upload a new one.
    configUrl: Type.String({ default: "https://lobby-config.beyondallreason.dev/config.json" }),
    rapidHost: Type.String({ default: "repos-cdn.beyondallreason.dev" }),
    rapidGame: Type.String({ default: "byar" }),
    engineReleaseUrl: Type.String({ default: "https://files-cdn.beyondallreason.dev/find" }),
    defaultMaps: Type.Array(Type.String(), { default: ["Quicksilver Remake 1.24", "Red Comet Remake 1.8"] }),
    latestGameVersion: Type.String({ default: "byar:test" }),
    defaultEngineVersion: Type.String({ default: "2025.06.21" }),
    initialPoolDataUrl: Type.String({ default: "https://pool-init.beyondallreason.dev" }),
    prdRapidUseStreamer: Type.String({ default: "false" }),
    prdRapidRepoMaster: Type.String({ default: "https://repos-cdn.beyondallreason.dev/repos.gz" }),
    prdHttpSearchUrl: Type.String({ default: "https://files-cdn.beyondallreason.dev/find" }),
    logUploadUrl: Type.String({ default: "https://log.beyondallreason.dev/" }),
    mapsMetadataUrl: Type.String({ default: "https://maps-metadata.beyondallreason.dev/latest/lobby_maps.validated.json" }),
    newsRssUrl: Type.String({ default: "https://www.beyondallreason.info/news/rss.xml" }),
    devlogRssUrl: Type.String({ default: "https://www.beyondallreason.info/microblogs/rss.xml" }),
    allowedUrlLinks: Type.Array(Type.String(), { default: ["https://bar-rts.com/replays", "https://www.beyondallreason.info/news"] }),
    replayServiceUrl: Type.String({ default: "https://bar-rts.com/replays" }),
    defaultServers: Type.Array(Type.String(), {
        default: ["wss://server4.beyondallreason.info", "wss://server5.beyondallreason.info", "wss://lobby-server-dev.beyondallreason.dev", "ws://localhost:4000"],
    }),
    replayDownloadUrl: Type.String({ default: "https://bar-rts.com/replays" }),
    // Default engine settings for BAR, sourced from:
    // https://github.com/beyond-all-reason/BYAR-Chobby/blob/master/dist_cfg/config.json
    springSettings: Type.Record(Type.String(), Type.Union([Type.String(), Type.Number()]), {
        default: {
            AdvUnitShading: 1,
            AdvMapShading: 1,
            AdvSky: 0,
            AllowDeferredMapRendering: 1,
            AllowDeferredModelRendering: 1,
            BuildWarnings: 0,
            BumpWaterBlurReflection: 1,
            BumpWaterDepthBits: 16,
            BumpWaterShoreWaves: 1,
            BumpWaterTexSizeReflection: 1024,
            CamTimeExponent: 4.0,
            CamTimeFactor: 1.0,
            CrossAlpha: 0,
            CubeTexSpecularExponent: 100,
            CubeTexGenerateMipMaps: 1,
            CubeTexSizeReflection: 1024,
            DisplayDebugPrefixConsole: 0,
            DualScreenMiniMapOnLeft: 1,
            FPSFOV: 90,
            FeatureDrawDistance: 10000,
            FeatureFadeDistance: 10000,
            ForceDisableShaders: 0,
            Fullscreen: 0,
            FullscreenEdgeMove: 1,
            GrassDetail: 0,
            GroundDecals: 2,
            GroundDetail: 200,
            GroundScarAlphaFade: 1,
            HangTimeout: 30,
            HardwareCursor: 1,
            InitialNetworkTimeout: 0,
            LODScale: 1.0,
            LODScaleReflection: 1.0,
            LODScaleRefraction: 1.0,
            LODScaleShadow: 1.0,
            LuaGarbageCollectionMemLoadMult: 2.0,
            LogFlush: 0,
            LuaShaders: 1,
            LoadingMT: 0,
            MaxParticles: 20000,
            MaxSounds: 256,
            MaximumTransmissionUnit: 0,
            MaxTextureAtlasSizeX: 8192,
            MaxTextureAtlasSizeZ: 8192,
            MiddleClickScrollSpeed: -0.005,
            MinimapOnLeft: 1,
            MouseDragScrollThreshold: 0.3,
            MoveWarnings: 0,
            MSAA: 1,
            MSAALevel: 4,
            NormalMapping: 1,
            ReconnectTimeout: 0,
            Roam: 1,
            ReflectiveWater: 3,
            ScrollWheelSpeed: -20,
            Shadows: 1,
            ShadowMapSize: 2048,
            ShowClock: 0,
            ShowFps: 0,
            ShowSpeed: 0,
            SmoothLines: 1,
            TreeRadius: 1000,
            UnitIconDist: 160,
            UnitLodDist: 999999,
            UnitIconsAsUI: 1,
            UnitIconScaleUI: 1.05,
            UnitIconFadeVanish: 2700,
            UnitIconFadeStart: 3000,
            UnitIconFadeAmount: 0.1,
            UsePBO: 1,
            Water: 4,
            WindowedEdgeMove: 1,
            WindowPosX: 0,
            WindowPosY: 0,
            snd_general: 100,
            snd_volmaster: 30,
            snd_volmusic: 30,
            snd_airAbsorption: 0.35,
            ui_opacity: 0.6,
            UseNetMessageSmoothingBuffer: 0,
            NetworkLossFactor: 2,
            MaxDynamicModelLights: 0,
            LinkOutgoingBandwidth: 262144,
            LinkIncomingSustainedBandwidth: 1048576,
            LinkIncomingPeakBandwidth: 1048576,
            LinkIncomingMaxPacketRate: 2048,
        },
    }),
});

export const updateConfigSchema = Type.Partial(configSchema);
export type TUpdateConfigSchema = Static<typeof updateConfigSchema>;
