// SPDX-FileCopyrightText: 2025 The BAR Lobby Authors
//
// SPDX-License-Identifier: MIT
/**
 * Generates src/main/content/game/campaign.ts from the campaign JSON Schema.
 *
 * Usage:  node --import=tsx tools/generate-campaign-types.ts
 *
 * The output file is auto-generated - do not edit it by hand.
 */
import { compile } from "json-schema-to-typescript";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SCHEMA_PATH = path.resolve(__dirname, "../src/main/content/game/schemas/campaign.schema.json");
const OUTPUT_PATH = path.resolve(__dirname, "../src/main/content/game/generated/campaign.ts");

const BANNER =
    "// THIS FILE IS AUTO-GENERATED from schemas/campaign.schema.json.\n" +
    "// Run `npm run generate:campaign` (or `npm start`) to regenerate.\n" +
    "// Do not edit this file manually.";
async function main() {
    const schemaText = await fs.promises.readFile(SCHEMA_PATH, "utf8");
    const schema = JSON.parse(schemaText) as object;
    const generated = await compile(schema, "", {
        bannerComment: BANNER,
        additionalProperties: false,
        unknownAny: false,
        strictIndexSignatures: false,
    });
    await fs.promises.mkdir(path.dirname(OUTPUT_PATH), { recursive: true });
    await fs.promises.writeFile(OUTPUT_PATH, generated, "utf8");
    console.log("Generated " + path.relative(process.cwd(), OUTPUT_PATH));
}
main().catch((error) => {
    console.error(error);
    process.exit(1);
});
