// SPDX-FileCopyrightText: 2025 The BAR Lobby Authors
//
// SPDX-License-Identifier: MIT
/**
 * Generates src/main/content/game/generated/*.ts from the JSON Schemas in
 * src/main/content/game/schemas, which are copies of the schemata shipped in the game archive.
 *
 * Usage:  node --import=tsx tools/generate-schema-types.ts
 *
 * The output files are auto-generated - do not edit them by hand.
 */
import { compile } from "json-schema-to-typescript";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SCHEMA_DIR = path.resolve(__dirname, "../src/main/content/game/schemas");
const OUTPUT_DIR = path.resolve(__dirname, "../src/main/content/game/generated");

const SCHEMAS = ["campaign", "manifest", "mission"];

function banner(name: string) {
    return `// THIS FILE IS AUTO-GENERATED from schemas/${name}.schema.json.
// Run \`npm run generate:schemas\` (or \`npm start\`) to regenerate.
// Do not edit this file manually.`;
}

async function generate(name: string) {
    const schemaText = await fs.promises.readFile(path.join(SCHEMA_DIR, `${name}.schema.json`), "utf8");
    const schema = JSON.parse(schemaText) as object;
    const generated = await compile(schema, "", {
        bannerComment: banner(name),
        additionalProperties: false,
        unknownAny: false,
        strictIndexSignatures: false,
    });
    const outputPath = path.join(OUTPUT_DIR, `${name}.ts`);
    await fs.promises.writeFile(outputPath, generated, "utf8");
    console.log("Generated " + path.relative(process.cwd(), outputPath));
}

async function main() {
    await fs.promises.mkdir(OUTPUT_DIR, { recursive: true });
    for (const name of SCHEMAS) {
        await generate(name);
    }
}
main().catch((error) => {
    console.error(error);
    process.exit(1);
});
