/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/debug/': RouteRecordInfo<'/debug/', '/debug', Record<never, never>, Record<never, never>>,
    '/debug/b': RouteRecordInfo<'/debug/b', '/debug/b', Record<never, never>, Record<never, never>>,
    '/debug/controls': RouteRecordInfo<'/debug/controls', '/debug/controls', Record<never, never>, Record<never, never>>,
    '/debug/font': RouteRecordInfo<'/debug/font', '/debug/font', Record<never, never>, Record<never, never>>,
    '/debug/script-launcher': RouteRecordInfo<'/debug/script-launcher', '/debug/script-launcher', Record<never, never>, Record<never, never>>,
    '/debug/test': RouteRecordInfo<'/debug/test', '/debug/test', Record<never, never>, Record<never, never>>,
    '/debug/test2': RouteRecordInfo<'/debug/test2', '/debug/test2', Record<never, never>, Record<never, never>>,
    '/library/': RouteRecordInfo<'/library/', '/library', Record<never, never>, Record<never, never>>,
    '/library/commands': RouteRecordInfo<'/library/commands', '/library/commands', Record<never, never>, Record<never, never>>,
    '/library/guides': RouteRecordInfo<'/library/guides', '/library/guides', Record<never, never>, Record<never, never>>,
    '/library/maps/[id]': RouteRecordInfo<'/library/maps/[id]', '/library/maps/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/library/maps/maps': RouteRecordInfo<'/library/maps/maps', '/library/maps/maps', Record<never, never>, Record<never, never>>,
    '/library/units': RouteRecordInfo<'/library/units', '/library/units', Record<never, never>, Record<never, never>>,
    '/news/': RouteRecordInfo<'/news/', '/news', Record<never, never>, Record<never, never>>,
    '/news/overview': RouteRecordInfo<'/news/overview', '/news/overview', Record<never, never>, Record<never, never>>,
    '/play/': RouteRecordInfo<'/play/', '/play', Record<never, never>, Record<never, never>>,
    '/play/campaign': RouteRecordInfo<'/play/campaign', '/play/campaign', Record<never, never>, Record<never, never>>,
    '/play/customLobbies': RouteRecordInfo<'/play/customLobbies', '/play/customLobbies', Record<never, never>, Record<never, never>>,
    '/play/matchmaking': RouteRecordInfo<'/play/matchmaking', '/play/matchmaking', Record<never, never>, Record<never, never>>,
    '/play/menu': RouteRecordInfo<'/play/menu', '/play/menu', Record<never, never>, Record<never, never>>,
    '/play/scenarios': RouteRecordInfo<'/play/scenarios', '/play/scenarios', Record<never, never>, Record<never, never>>,
    '/play/skirmishVsAi': RouteRecordInfo<'/play/skirmishVsAi', '/play/skirmishVsAi', Record<never, never>, Record<never, never>>,
    '/play/tournaments': RouteRecordInfo<'/play/tournaments', '/play/tournaments', Record<never, never>, Record<never, never>>,
    '/profile/[userId]': RouteRecordInfo<'/profile/[userId]', '/profile/:userId', { userId: ParamValue<true> }, { userId: ParamValue<false> }>,
    '/watch/': RouteRecordInfo<'/watch/', '/watch', Record<never, never>, Record<never, never>>,
    '/watch/replays': RouteRecordInfo<'/watch/replays', '/watch/replays', Record<never, never>, Record<never, never>>,
  }
}
